apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image:   
 us-central1-docker.pkg.dev/<your-project>/<your-repository>/fastapi:latest
        ports:
        - containerPort: 8000
        env:
        - name: SOME_ENV_VAR
          value: "some_value"  # Example environment variable

apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
  - protocol: TCP
    port: 80
    targetPort:   
 8000
